out_path: "tests/data/output/"
action: move                      # copy, move
movie_format: "{n} ({y})"         # The Matrix (1999)
movie_exts:
  - ".avi"
  - ".mp4"
  - ".m4v"
  - ".mkv"
logger:
  path: pymdb-rename.log
  file: 
    level: logging.DEBUG
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  stdout:
    level: logging.ERROR
    format: "%(levelname)s: %(name)s - %(message)s"
  format: 
