out_path: "/mnt/lilnas/movies/"
action: copy
movie_format: "{n} ({y})"
movie_exts:
  - ".avi"
  - ".mp4"
  - ".m4v"
  - ".mkv"
logger:
  path: pymdb-rename.log
  filelevel: logging.DEBUG        # DEBUG, INFO, WARNING, ERROR
  stdoutlevel: logging.INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"